JavaFlorist/Areas/Admin/Controllers/UserAuthenticationController.cs
using JavaFlorist.Models.DTO;
using JavaFlorist.Repositories.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace JavaFlorist.Areas.Admin.Controllers
{
        [Authorize(Roles = "Admin")]
    public class UserAuthenticationController : Controller
    {
        private IUserAuthenticationService authService;
        private readonly IFileService _fileService;
        public UserAuthenticationController(IUserAuthenticationService authService, IFileService fileService)
        {
            this.authService = authService;
            _fileService = fileService;
        }
        [Area("Admin")]
        public async Task<IActionResult> UserList()
        {
            var usersInRole = await authService.GetAllUsersInRole("User");
            return View(usersInRole);
        }
        [Area("Admin")]

        public async Task<IActionResult> AdminList(string search)
        {
            var admins = await authService.GetAllUsersInRole("Admin");
            if (!string.IsNullOrEmpty(search))
            {
                admins = admins.Where(d => d.UserName.Contains(search, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            ViewBag.SearchTerm = search;

            return View(admins);
        }

        [Area("Admin")]
        public async Task<IActionResult> Delete(string userId)
        {
            var isDeleted = await authService.DeleteUser(userId);
            if (isDeleted)
            {
                TempData["msg"] = "Deleted Successfully";
                return RedirectToAction(nameof(AdminList));
            }
            else
            {
                TempData["msg"] = "Error on server side";
                return RedirectToAction(nameof(AdminList));
            }

          
        }

        [Area("Admin")]
        public IActionResult Add()
        {
            return View();
        }

        [Area("Admin")]
        [HttpPost]
        public async Task<IActionResult> Add(RegistrationModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData["msg"] = "Passwords do not match";
                return View(model);
            }
               
            model.Role = "Admin";

            if (model.ImageFile != null)
            {
                var fileReult = this._fileService.SaveImage(model.ImageFile);
                if (fileReult.Item1 == 0)
                {
                    TempData["msg"] = "File could not saved";
                    return View(model);
                }
                var imageName = fileReult.Item2;
                model.ProfilePicture = imageName;
            }

            var result = await authService.AddUserAdmin(model);
            if (result.StatusCode == 1)
            {
                TempData["msg"] = result.Message;
                return View(model);
            }
            else if (result.StatusCode == 2)
            {
                TempData["msg"] = result.Message;
                return View(model);
            }
            TempData["msg"] = result.Message;
            //TempData["RegisteredSuccessfully"] = true;
            return RedirectToAction(nameof(AdminList));
        }
    }
}

JavaFlorist/Controllers/UserAuthenticationController.cs
using JavaFlorist.Models.DTO;
using JavaFlorist.Repositories.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Configuration;

namespace JavaFlorist.Controllers
{
    public class UserAuthenticationController : Controller
    {
        private IUserAuthenticationService authService;
        private readonly IFileService _fileService;
        public UserAuthenticationController(IUserAuthenticationService authService, IFileService fileService)
        {
            this.authService = authService;
            _fileService = fileService;
        }


        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegistrationModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            model.Role = "User";

            var result = await authService.RegisterAsync(model);
            if(result.StatusCode == 1)
            {
                TempData["msg"] = result.Message;
                return View();
            }else if (result.StatusCode == 2)
            {
                TempData["msg"] = result.Message;
                return View();
            }
            TempData["msg"] = result.Message;
            TempData["RegisteredSuccessfully"] = true;
            return Redirect("/Home/Index");
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var result = await authService.LoginAsync(model);
            if (result.StatusCode == 1)
                return RedirectToAction("Index", "Home");
            else
            {
                TempData["msg"] = "Could not logged in..";
                return RedirectToAction(nameof(Login));
            }
        }
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await authService.LogoutAsync();
            return RedirectToAction(nameof(Login));
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UpdateProfile(UserCustomerModel model)
        {
     

            if (model.ImageFile != null)
            {
                var fileReult = this._fileService.SaveImage(model.ImageFile);
                if (fileReult.Item1 == 0)
                {
                    TempData["msg"] = "File could not saved";
                    return View(model);
                }
                var imageName = fileReult.Item2;
                model.ProfilePicture = imageName;
            }
            var result = await authService.Update(model);
            if(result.StatusCode == 1)
            {
                TempData["power"] = true;
                TempData["msg"] = result.Message;
                return Redirect("/Home/Index");
            }
            else if (result.StatusCode == 2)
            {
                TempData["power"] = true;
                TempData["msg"] = result.Message;
                return Redirect("/Home/Index");

            }
            TempData["power"] = true;
            TempData["msg"] = result.Message;
            return Redirect("/Home/Index");

        }



        public IActionResult CustomerCount()
        {
            var data = authService.GetAllUsers();
            var count = data.Result.Count;
            return Json(count);
        }


        [Authorize]
        public IActionResult ChangePassword()
        {
            // Your change password view/page
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
        {
            if (model == null)
            {
                ModelState.AddModelError(string.Empty, "Invalid data");
                return View(model);
            }

            var result = await authService.ChangePasswordAsync(model);

            if (result.StatusCode == 1)
            {
                TempData["SuccessMessage"] = result.Message;
                return Redirect(Request.Headers["referer"].ToString());
            }
            else
            {
                ModelState.AddModelError(string.Empty, result.Message);
                return View(model);
            }
        }
    }
}

JavaFlorist/Areas/Admin/Views/UserAuthentication/Add.cshtml
@model JavaFlorist.Models.DTO.RegistrationModel;
@{
    ViewData["Title"] = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}

<div class="container-fluid">
    <div class="container-fluid">
        <div class="card">
            <div class="card-body mt-3">
                <h5 class="card-title fw-semibold mb-4 mt-5">Add Admin</h5>
                <div class="card">
                    <div class="card-body">
                        <form class="w-40" method="post" asp-action="Add" asp-controller="UserAuthentication" style="background-color:#ffffff;border-radius:5px;padding:24px" enctype="multipart/form-data">
                            <!-- 2 column grid layout with text inputs for the first and last names -->
                            <div class="row mb-4">
                                <div class="col">
                                    <div class="form-outline">
                                        <label class="form-label" asp-for=" Username">Username</label>
                                        <input type="text" asp-for="Username" name="Username" placeholder="Please Enter Username !" class="form-control" style="border: 1px solid #e8e8e8;" required />
                                    </div>
                                    <div class="message-box pd-x-28 error">
                                        <span asp-validation-for="name"> </span>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-outline">
                                        <label class="form-label" asp-for="ImageFile">Thumnail</label>
                                        <input type="file" asp-for="ImageFile" name="ImageFile" class="form-control" style="border: 1px solid #e8e8e8;" required />
                                    </div>
                                    <div class="message-box pd-x-28 error">
                                        <span asp-validation-for="ImageFile"> </span>
                                    </div>
                                </div>
                            </div>
                            <div class="row mb-4">
                                <div class="form-outline ">
                                    <label class="form-label" asp-for="Email">Email</label>
                                    <input type="text" asp-for="Email" name="Email" placeholder="Please Enter Email ! " class="form-control" style="border: 1px solid #e8e8e8;" required />
                                </div>
                                <div class="message-box pd-x-28 error ">
                                    <span asp-validation-for="Email"> </span>
                                </div>

                            </div>
                            <!-- 2 column grid layout with text inputs for the first and last names -->
                            <div class="row mb-4">
                                <div class="col">
                                    <div class="form-outline">
                                        <label class="form-label" asp-for="Password">Password</label>
                                        <input type="text" class="form-control" placeholder="Please Enter Password !" name="Password" asp-for="Password" required />
                                    </div>
                                    <div class="message-box pd-x-28 error">
                                        <span asp-validation-for="Password"></span>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-outline">
                                        <label class="form-label" asp-for="PasswordConfirm">PasswordConfirm</label>
                                        <input type="text" asp-for="PasswordConfirm" name="PasswordConfirm" placeholder="Please Enter Confirm Password !" class="form-control" style="border: 1px solid #e8e8e8;" required />
                                    </div>
                                    <div class="message-box pd-x-28 error">
                                        <span asp-validation-for="PasswordConfirm"> </span>
                                    </div>
                                </div>
                            </div>

                          
                            @if (TempData["msg"] != null)
                            {
                                <div class="alert alert-danger mt-3" role="alert">
                                    @TempData["msg"]
                                </div>
                            }
                            <!-- Submit button -->
                            <button type="submit" class="btn btn-danger btn-block mt-4 mb-6">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

JavaFlorist/Areas/Admin/Views/UserAuthentication/AdminList.cshtml
@model IEnumerable<JavaFlorist.Models.Domain.ApplicationUser>;
@{
    ViewData["Title"] = "AdminList";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}



<div class="container-fluid">

    <div class="row">

        <div class="col-lg-12 d-flex align-items-stretch">
            <div class="card w-100">
                <div class="card-body p-4" style="margin-top:80px;">
                    <h5 class="card-title fw-semibold mb-4">Administrantion Account List</h5>
                    <div class="d-flex">
                        <a href="/Admin/UserAuthentication/Add" class="btn btn-primary">Add</a>
                        <form method="get" action="/Admin/UserAuthentication/AdminList" style="padding-left:10px">
                            <div class="d-flex" style="gap:5px;">
                                <input type="text" class="form-control" id="searchInput" name="search" value="@ViewBag.SearchTerm" />
                                <button type="submit" class="btn btn-primary">Search</button>
                            </div>
                        </form>

                    </div>
                    <div class="table-responsive">
                        @if (TempData["msg"] != null)
                        {
                            <div class="alert alert-success mt-3" role="alert">
                                @TempData["msg"]
                            </div>
                        }
                        <table class="table text-nowrap mb-0 align-middle">
                            <thead class="text-dark fs-4">
                                <tr>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Avatar</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Username</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Email</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Action</h6>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var user in Model.Reverse())
                                {
                                    <tr>
                                        <td style="display:none">@user.Id</td>
                                        <td class="border-bottom-0">
                                            <img src="/Uploads/@user.ProfilePicture" style="height:100px;width:100px;" />
                                        </td>
                                        <td class="border-bottom-0">
                                            <p class="mb-0 fw-normal">@user.UserName</p>
                                        </td>
                                        <td class="border-bottom-0">
                                            <p class="mb-0 fw-normal">@user.Email</p>
                                        </td>
                                        <td class="border-bottom-0">
                                            <a  onclick="return window.confirm('Are you want delete discount have name @user.UserName')"   href="/Admin/UserAuthentication/Delete?UserId=@user.Id" class="btn btn-danger">Delete</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div> 

JavaFlorist/Areas/Admin/Views/UserAuthentication/UserList.cshtml
@model IEnumerable<JavaFlorist.Models.Domain.ApplicationUser>;
@{
    ViewData["Title"] = "UserList";
    Layout = "~/Areas/Admin/Views/Shared/_AdLayout.cshtml";
}



<div class="container-fluid">

    <div class="row">

        <div class="col-lg-12 d-flex align-items-stretch">
            <div class="card w-100">
                <div class="card-body p-4" style="margin-top:80px;">
                    <h5 class="card-title fw-semibold mb-4">Users Account List</h5>
                    <div class="table-responsive">
                        <table class="table text-nowrap mb-0 align-middle">
                            <thead class="text-dark fs-4">
                                <tr>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Id</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Avatar</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Username</h6>
                                    </th>
                                    <th class="border-bottom-0">
                                        <h6 class="fw-semibold mb-0">Email</h6>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var user in Model)
                                {
                                    <tr>
                                        <td style="display:none">@user.Id</td>
                                        <td class="border-bottom-0"><h6 class="fw-semibold mb-0">1</h6></td>
                                        <td class="border-bottom-0">
                                            @if(user.ProfilePicture == null)
                                            {
                                                <img src="/img//Avatar-Default.jpg" style="height:100px;width:100px;" />

                                            }else{
                                                <img src="/Uploads/@user.ProfilePicture" style="height:100px;width:100px;" />
                                            }
                                        </td>
                                        <td class="border-bottom-0">
                                            <p class="mb-0 fw-normal">@user.UserName</p>
                                        </td>
                                        <td class="border-bottom-0">
                                            <p class="mb-0 fw-normal">@user.Email</p>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div> 